### ISSUE TITLE
Feature: Anunciar las vacantes

### ISSUE THREAD

**Issue by copy-bin** [emilioramirez/pochobot#4]
Estaría bueno poder anunciar cuantas vacantes hay: 
El creador puede aumentar las vacantes

**Comment by emilioramirez** [comment]
Si en el nombre del menu agregas un numero por ejemplo "Guiso para 8 personas", pocho activa el control de vacantes usando ese 8 como limite de vacantes (se incluye al creador del almuerzo dentro de esos 8)
