### ISSUE TITLE
Feature: Poder cerrar el cupo

### ISSUE THREAD

**Issue by copy-bin** [emilioramirez/pochobot#5]
El administrador debe poder cerrar el cupo, al cerrar el cupo, los inscriptos hasta el momento son informados que quedaron contados.
Todos los demas que se quieran sumar no podrán sumarse. recibiran mensaje "cupa cerrado"

**Comment by emilioramirez** [comment]
Al momento de crear el almuerzo si se pone un numero en el nombre pocho lo toma como numero de vacantes, y no se va a poder agregar mas de esa cantidad de comenzales, cuando se llena el cupo pocho anuncia que se lleno el cupo y no se puede sumar mas nadie.

**Comment by copy-bin** [comment]
Copadoo!

2015-02-01 18:17 GMT-03:00 Emilio Ramirez notifications@github.com:
